name: Deploy OSB

on: 
  push:
    branches: 
      - main
      - 'release/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
      HERKO_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
  
