name: Deploy OSB

on: 
  push:
    branches: 
      - main
      - 'release/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
